COLUMNS:
  age : int64
  job : object
  marital : object
  education : object
  default : object
  balance : int64
  housing : object
  loan : object
  contact : object
  day : int64
  month : object
  duration : int64
  campaign : int64
  pdays : int64
  previous : int64
  poutcome : object
  y : int64
  # y is the target variable, indicating if the client subscribed to a term deposit

TARGET_COLUMN:
  name: y
